name = "leagueml-api"
type = "javascript"
zone_id = "f6c9b8379ae4e9e7ae13ee1d17c5a693"
account_id = "9b4e8a5306252de7d3ebd878e5e80e27"
route = "api.league.ml/*"
compatibility_date = "2022-03-12"

[build]
command = "pnpm install && pnpm run build"
[build.upload]
format = "service-worker"

[durable_objects]
bindings = [
  # { name = "RIOT_RATE_LIMIT", class_name = "RateLimiter" }
]